### ISSUE TITLE
Разработать дизайн приложения принтера

### ISSUE THREAD

**Issue by dyakovri** [profcomff/print-winapp#1]
Нынешний дизайн был придуман на ходу, не очень симпатичный, сливается с фоном, мешает работе с приложениями

Нужен дизайнер, который проработает варианты использования и нарисует удобный и красивый пользовательский интерфейс

**Comment by mrerro** [comment]
https://www.figma.com/file/8L6gslGdkrBO4APVtO9mj0/Untitled?node-id=1%3A2
