### ISSUE TITLE
Улучшательства

### ISSUE THREAD

**Issue by dyakovri** [profcomff/print-winapp#21]
- [ ] Добавить настройку пути к временной папки в конфиг
- [ ] Перенести временную папку в %TEMP% https://stackoverflow.com/a/946017
- [ ] Добавить настройку "проверять автозагрузку"
- [ ] Если при закрытии приложения "проверять автозагрузку" и ярлыка на экзешник не существует в папке автозагрузки, создать

**Comment by mrerro** [comment]
![image](https://user-images.githubusercontent.com/13213573/198593445-40dea454-dbae-4183-82a3-11afe1282f19.png)
