### ISSUE TITLE
Безопасная перезагрузка приложения

### ISSUE THREAD

**Issue by dyakovri** [profcomff/print-winapp#38]
- [x] Перезагрузка по коду REBOOT, которая будет закрывать текущее окно и открывать новое. Без передачи управления системы пользователю.
- [x] Перезагрузка приложения аналогично по команде с сервера

**Comment by mrerro** [comment]
Переделаю работу приложения независимо от окна и в ручном режиме буду закрывать программу только в нужных случаях полностью. Воспользуюсь свойством [Application.ShutdownMode](https://learn.microsoft.com/ru-RU/dotnet/api/system.windows.application.shutdownmode?view=windowsdesktop-7.0&viewFallbackFrom=net-7.0) = `OnExplicitShutdown`
